### ISSUE TITLE
YAML Reference doesn't have an example for "accessor"

### ISSUE THREAD

**Issue by wheelsandcogs** [schmittjoh/JMSSerializerBundle#148]
Hi - I'm trying to deserialize a FOSUserBundle User from JSON, but my password is being stored in plaintext.

I've discovered this is because I need to get the deserializer to use $user->setPlainPassword() rather than $user->setPassword(), so I need to set the Accessor method - but there's no example of how to do this in the YAML reference. 

Here's what I tried:

```
FOS\UserBundle\Model\User:
    properties:
        username:
            type: string
            groups: [ignored]
        usernameCanonical:
            type: string
            groups: [ignored]
        email:
            access_type: public_method
            type: string
            groups: [import, export]
        emailCanonical:
            access_type: public_method
            type: string
            groups: [ignored]
        enabled:
            type: boolean
            groups: [ignored]
        salt:
            type: string
            groups: [ignored]
        password:
            accessor: { setter: setPlainPassword }
            type: string
            groups: [import]
        locked:
            type: boolean
            groups: [ignored]
        expired:
            type: boolean
            groups: [ignored]
        roles:
            type: array
            groups: [ignored]
```

But that doesn't appear to work. Is the format incorrect or is Accessor only supported via annotations?
