### ISSUE TITLE
Configured order of custom handlers is ignored

### ISSUE THREAD

**Issue by pluess** [schmittjoh/JMSSerializerBundle#174]
The documentation at http://jmsyst.com/de/bundles/JMSSerializerBundle/master/cookbook/custom_handlers sais: _The order in which the handlers are listed in the “handlers” section defines in which they are called while processing._

I'm not 100% sure what this means. My understanding is that I can put something like this

``` yaml
jms_serializer:
    handlers:
        my_custom_handler: true
        object_based: false
        datetime:
            format: "Y-m-dTH:i:s"
            default_timezone: "UTC"
        array_collection: true
        form_error: true
        constraint_violation: true
```

into app/config/config.yml which should make sure that my_custom_handler is always called first.

But looking at JMSSerializerExtension::load line 77ff makes clear that this configuration is ignored. The order depends on the order the configureSerializerExtension methods are called on the bundles.

``` php
        foreach ($config['handlers'] as $k => $handlerConfig) {
            $id = $this->factories[$k]->getHandlerId($container, $handlerConfig);
            $type = $this->factories[$k]->getType($handlerConfig);

            if (0 !== ($type & HandlerFactoryInterface::TYPE_SERIALIZATION)) {
                $serializationHandlers[] = new Reference($id);
            }

            if (0 !== ($type & HandlerFactoryInterface::TYPE_DESERIALIZATION)) {
                $deserializationHandlers[] = new Reference($id);
            }
        }
```

My sugestion would be to change the above code to obey what is configured in the handler section. A question that arises by implenting it that way is: What should happen to handlers which are not listed there. I think they should be ignored (and the developer should be warned, but I don't know how to do that).
