### ISSUE TITLE
Strange behavior with groups : relation is no more serialized

### ISSUE THREAD

**Issue by vincentdieltiens** [schmittjoh/JMSSerializerBundle#200]
Hi,

I've a strange behavior when i use groups.
When i serialize a Doctrine entity with one relation, the relation is not serialized anymore when using groups.

Here is my configuration : I have 2 entities  -- Customer and User -- with a many-to-one relation from Customer to User on the field "created_by".

Here is a piece of "Entitiy.Customer.yml" :

```
Dieltiens\Bundle\CustomerBundle\Entity\Customer:
    exclusion_policy: NONE
    properties:
        id:
            expose: true
            groups: [list]
        company_name:
            expose: true
            groups: [list]

        # other fields

        created_by:
            expose: true
            groups: [list, detail]
            type: Dieltiens\Bundle\UserBundle\Entity\User
```

In my Symfony controller, the code that is serializing is :

```
$customers = $this->getDoctrine()->getRepository('DieltiensCustomerBundle:Customer')->findAll();
$serializer = $this->container->get('serializer');
//$serializer->setGroups(array('list'));
$customers_json = $serializer->serialize($customers, 'json');
```

With the third line commented, it is working  i get the following response :

```
[{
  "id": 1,
  "company_name": "companyName",
   // other fields  
  "created_by": {
    "id": 1,
    "username": "Vincent",
    "password": "an hashed password"
  }
}]
```

With the third line uncommented, i get the following response :

```
[{
  "id": 1,
  "company_name": "Diel",
  // other fields  
  "created_by": []
}]
```

It's very strange because between the to different results, nothing change except the line `$serializer->setGroups(array('list'));``

Also, the created_by value is an empty array  then I set the type as a User Entity.

Thanks,

Vincent
