### ISSUE TITLE
Can't configurate class which is in global namespace with YAML or XML

### ISSUE THREAD

**Issue by redexp** [schmittjoh/JMSSerializerBundle#217]
If some class which I want to serialize is in global namespace then I can't to configure it with config files, I can do that only with annotations.

If in app/config/config.yml I'll do like this

```
jms_serializer:
    metadata:
    directories:
            base-object:
                namespace_prefix: ""
                path: "@MyFooBundle/Resources/config/serializer"
```

then it will throw exception "Empty delimiter" because of strpos in FileLocator::findFileForClass on line 

```
if (0 !== strpos($class->getNamespaceName(), $prefix)) {
```

because $class->getNamespaceName() == "" and $prefix == ""
