### ISSUE TITLE
xml_root_name not working

### ISSUE THREAD

**Issue by alex88** [schmittjoh/JMSSerializerBundle#227]
I've this yml serializer config:

```
Acme\UserBundle\Entity\User:
    exclusion_policy: ALL
    xml_root_name: foobar
    properties:
        id:
            expose: true
        name:
            expose: true
```

and in the xml serialized output I get

```
<entry>
    <id>3</id>
    <name>
        <![CDATA[ Alessandro Tagliapietra ]]>
    </name>
</entry>
```

so the xml root isn't there..
Plus, a key->value array like

in json is

```
{"test":15,"test2":20}
```

but in xml
    <entry>15</entry>
    <entry>20</entry>

when I supposed to get

```
<test>15</test>
<test2>20</test2>
```
