### ISSUE TITLE
Unable to use Resource identifier for directories path in confing.yml

### ISSUE THREAD

**Issue by ftassi** [schmittjoh/JMSSerializerBundle#26]
Hi, 
I'm trying to define custom directory for serializer metadata, but I'm not able to define a resource for "path" key. 

Using resource identifier as documented file locator is unable to convert it to a valid path. 

This configuration wont work:

```
directories:
        any-name:
            namespace_prefix: My\FooBundle
            path: @MyFooBundle/Resources/config/serializer
```

And this will:

```
directories:
        any-name:
            namespace_prefix: My\FooBundle
            path: %kernel.root_dir%/../src/My/FooBundle/Resources/config/serializer
```

I think that Metadata\Driver\FileLocator is not able to convert @MyFooBundle/Resources/config/serializer in src/My/FooBundle/Resources/config/serializer.  
Maybe the bundle should use Symfony\Component\HttpKernel\Config\FileLocator ? 
Is simply a documentation error ?
