### ISSUE TITLE
Exclusion policy for entity relationships

### ISSUE THREAD

**Issue by drgomesp** [schmittjoh/JMSSerializerBundle#266]
Hi!

I have two entities, with `@ManyToOne` relationship between them.

``` php
class Customer
{
    /**
     * @ORM\OneToMany(targetEntity="ContactSubmission", mappedBy="customer")
     */
    private $contactSubmissions;
}
```

``` php
class ContactSubmission
{
    /**
     * @ORM\ManyToOne(targetEntity="Customer", inversedBy="contactSubmissions", cascade={"persist"})
     * @ORM\JoinColumn(name="customerId", referencedColumnName="id")
     */
    private $customer;
}
```

My exclusion policy works great for one of them, but the relational entity fields are not being excluded according to their policies.

This is what I have for the exclusion policy:

``` yaml
MyNamespace\MyBundle\Entity\ContactSubmission:
    exclusion_policy: ALL
    properties:
        customer:
            expose: true
            type: MyNamespace\MyBundle\Entity\Customer
        subject:
            expose: true
        message:
            expose: true
        date:
            expose: true
```

Is there anyway I can set a field to represent that relationship or something like that?
