### ISSUE TITLE
'public_method' access requires redundant property in class

### ISSUE THREAD

**Issue by calumbrodie** [schmittjoh/JMSSerializerBundle#280]
I'm finding that with a configuration like so:

```
Namespace\Bundle\CategoryBundle\Entity\Category:
  exclusion_policy: ALL
  properties:
    type:
      expose: true
      access_type: public_method
      type: string
      accessor:
        getter: getType
        setter: setType
```

The serialized entity does not contain this 'computed' property - unless I add the named property to my class..

eg This works:

```
<?php

class Category implements CategoryInterface
{

        protected $type;            

    public function getType()
    {
        return 'typeA'
    }

    public function setType($type)
    {
        throw new \Exception('type is a read only property');
    }

}
```

And this doesn't

```
<?php

class Category implements CategoryInterface
{

    public function getType()
    {
        return 'typeA'
    }

    public function setType($type)
    {
        throw new \Exception('type is a read only property');
    }

}
```
