### ISSUE TITLE
How can I force a property to serialize even if it's null?

### ISSUE THREAD

**Issue by dominte-ca** [schmittjoh/JMSSerializerBundle#293]
I want that all/some of the properties to appear in the serialization even if they are null. 

Could try by using `public_method` and force check on getters, but seems a ugly workaround

**Comment by GusAntoniassi** [comment]
Sorry for the necroposting, but I came here looking for how to configure null serialization in the `SerializerBuilder`. Turns out it is explained [in the docs](https://jmsyst.com/libs/serializer/master/configuration#setting-a-default-serializationcontext-factory).

```php
use JMS\Serializer\SerializationContext;

$serializer = JMS\Serializer\SerializerBuilder::create()
    ->setSerializationContextFactory(function () {
        return SerializationContext::create()
            ->setSerializeNull(true)
        ;
    })
    ->build()
;
```

**Comment by filipp-k** [comment]
Is it possible to serialize null only for specific property?

One of the json field of the API I need is nullable but required. I need to pass it even if it's null.

**Comment by goetas** [comment]
Unfortunately I think that you need a custom post serialize event listener registered on that type

**Comment by DavidGarciaCat** [comment]
Hello everyone,

I'd like to know if newer bundle versions require further changes.

I have the following settings in my `yaml` file (found in the [configuration reference](https://jmsyst.com/bundles/JMSSerializerBundle/master/configuration) web page):

```yaml
jms_serializer:

    # ...

    default_context:
        serialization:
            serialize_null: true
        deserialization:
            serialize_null: true
```

None of the `when@...` blocks reference the `serialize_null` field, so this setting should not be overridden.

I also have this PHP code in my Kernel View Event Listener (as [suggested above](https://github.com/schmittjoh/JMSSerializerBundle/issues/293#issuecomment-17763768)) to get the Controller's returned object and serialize it, so it can be returned as a JSON String in the `JsonResponse` I am adding to my `KernelView $event`:

```php
$context = SerializationContext::create()->setGroups($serializerGroups);
$context->setSerializeNull(true); // First reply in this issue suggests adding this call

$serializedData = $this->serializer->serialize(data: $data, format: 'json', context: $context);
```

My serializer config sets two fields for a user:

```yaml
App\Entity\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            type: string
            serialized_name: email
            nullable: false
        emailToConfirm:
            expose: true
            type: string
            serialized_name: email_to_confirm
            nullable: true
```

However, the 2nd field doesn't get rendered as part of my JSON response unless I set a value on that field

Any suggestions?

Thanks in advance,
