### ISSUE TITLE
Expose `field_name` with discriminator map

### ISSUE THREAD

**Issue by Sydney-o9** [schmittjoh/JMSSerializerBundle#336]
Is there a way to expose the field name when using a discriminator map?

``` yml
Acme\UserBundle\Entity\User:
  exclusion_policy: ALL
  discriminator:
        field_name: type
        map:
            userType1: Acme\UserBundle\Entity\userType1
            userType2: Acme\UserBundle\Entity\userType2
```

I tried:

```
//...
  properties:
    type:
      expose: true
```

But this doesn't work... any idea if this is possible?
