### ISSUE TITLE
Propel Collection Handler is not registered

### ISSUE THREAD

**Issue by tseho** [schmittjoh/JMSSerializerBundle#349]
Hi,

PropelCollectionHandler is not registered as a service, so if you try to use it, you have the problem described here : https://groups.google.com/d/msg/symfony2/FqiqJ2dqAM8/4CKlej8PM-AJ

It could be fixed with :

```
parameters:
    jms_serializer.propel_collection_handler.class: JMS\Serializer\Handler\PropelCollectionHandler

services:
    jms_serializer.propel_collection_handler:
        class: %jms_serializer.propel_collection_handler.class%
        tags:
            - { name: jms_serializer.subscribing_handler }
```

I'm aware that not everyone need this service, so should we add it to Resources/config/services.xml or write it into the documentation ?
