### ISSUE TITLE
Cannot fully serialized a property with type ArrayCollection<abstract type>

### ISSUE THREAD

**Issue by v1nc3n4** [schmittjoh/JMSSerializerBundle#366]
Hi,

I'm working with inheritance, and I cannot succeed in serializing an ArrayCollection property of an abstract type, using YAML configuration. For instance:

```
// This is the main class being serialized
class Entity
{
    private $elements;
}
```

The Entity class has this serializer configuration:

```
Entity:
    properties:
        elements:
            type: 'ArrayCollection<AbstractElement>'
```

The collection contains instances of this abstract class:

```
abstract class AbstractElement
{
    // A successfully serialized property.
    private $id;

    /**
     * @return mixed The data in this model. It's up to each concrete sub-class to define
     * the exact type returned.
     */
    public abstract function getValue();
}
```

The AbstractElement class has this serializer configuration:

```
AbstractElement:
    properties:
        id:
            type: integer
```

A concrete implementation of this abstract class is:

```
class Element extends AbstractElement
{
    // This property is never serialized!
    $private $value;
}
```

The Element class has this serializer configuration:

```
Element:
    properties:
        value:
            type: string
```

The property 'value' in the Element class is never serialized, when attempting to serialize an instance of the Entity class containing one element.
It seems that drivers don't look at all configuration files, for each class in the hierarchy.
Drivers look only at the 'AbstractElement' metadata defined in 'ArrayCollection<AbstractElement>', and don't see the 'value' property in the Element sub-class.
Thus, my question is simple: are abstraction and inheritance supported when serializing collections?
Feel free to tell me if I've done something wrong!

Thanks in advance for your help.
BR
