### ISSUE TITLE
Mapping for child classes not working as expected

### ISSUE THREAD

**Issue by AntonStoeckl** [schmittjoh/JMSSerializerBundle#386]
Hi there,

probably this is a known issue, at least I could not find it ...

We have a class FooCollection that extends an abstract Class Collection. All properties and methods are in parent class, the child is only
1) a marker class
2) there to be able to have different serializer configs for different of those child collections

Here's what we have:

```
MyNamespace\FooCollection:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        foo:
            expose: true
            type: array<SomeObject>
            read_only: true
        count:
            expose: true
            type: integer
            read_only: true
```

```
class FooCollection extends Collection
{
}
```

```
abstract class Collection
{
    /**
     * @var array
     */
    protected $items;

    /**
     * @var integer
     */
    protected $count;

    /**
     * @param array $items
     */
    public function __construct(array $items = array())
    {
        $this->items = $items;
        $this->count = count($items);
    }

    /**
     * {@inheritdoc}
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * {@inheritdoc}
     */
    public function getCount()
    {
        return $this->count;
    }
}
```

Now what happens is that the "properties" mapping is completely ignore. I found out this is because there is the parent class without a mapping. The serializer simply takes the properties from the parent class and serializes them. The mapping in itself is applied (trust me).
The workaround is to use only virtual properties (getItems, getCount), in this case it does not serialize the flat properties.

For me this does not act like a feature, so I assume it's a bug.

Regards, Anton
