### ISSUE TITLE
Naming strategy for embedded form

### ISSUE THREAD

**Issue by mehdi-ghezal** [schmittjoh/JMSSerializerBundle#396]
Hi all,

I have an API build with FOSRestBundle. I use the Form component to process my entities and validate. I disable camelcase naming strategy with this configuration :

``` yml
parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
```

Everything ok with a simple form but when I have an embedded form the name of embedded attributes is transform to camel case.

A simple example : 

``` yml
# Company Serialization configuration
Acme\AcmeBundle\Model\Company:
    exclusion_policy: ALL
    xml_root_name: company
    properties:
        name:
            type: string
            expose: true
        ownerName:
            type: string
            expose: true
        address:
            type: Acme\AcmeBundle\Model\Address
            expose: true

# Address Serialization configuration
Acme\AcmeBundle\Model\Address:
    exclusion_policy: ALL
    xml_root_name: address
    properties:
        street:
            type: string
            expose: true
        postalCode:
            type: string
            expose: true
```

With forms like that :

``` php
class CompanyFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', 'text', array(
                'label' => 'name'
            ))
            ->add('ownerName', 'text', array(
                'label' => 'ownerName'
            ))
            ->add('address', 'address', array(
                'label' => 'address'
            ));
    } 
}

class AddressFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('street', 'text', array(
                'label' => 'street'
            ))
            ->add('postalCode', 'text', array(
                'label' => 'postalCode'
            ))
    } 
}
```

When I process my company form, the validation failed beacause attribute is transform to camelcasing and not bind : 

``` json
{
    "code": 400,
    "message": "Validation Failed",
    "errors": {
        "errors": [
            "The postal code cannot be empty",
            "This form should not contain extra fields."
        ],
        "children": {
            "name": {
                "errors": []
            },
            "ownerName": {
                "errors": []
            },
            "address": {
                "children": {
                    "street": [],
                    "postal_code": [],
                }
            }
        }
    }
}
```

As you can see, postal_code was transform to camelcase and we have an error for extra fields. Am I missing something in configuration ?

Thank you for your answers
