### ISSUE TITLE
[Feature] Apply exclusión policity by groups

### ISSUE THREAD

**Issue by rkmax** [schmittjoh/JMSSerializerBundle#401]
It would be great if you could define a policy exclusion for group.
## Example

``` yaml
# resource/serializer/Document.Foo.yml
MyBundle\Document\Foo:
  exclusion_policy: ALL
  exclusion_policy_groups:
      foo: ALL
      bar: NONE
  properties:
       property_a:
           expose: true
           policy_group: foo           
       property_b:
           exclude: false
           policy_group: bar
```
## Example 2

``` yaml
# resource/serializer/Document.Foo.yml
MyBundle\Document\Foo:
  foo: # Group name
    exclusion_policy: ALL
    properties:
      property_a:
        expose: true
  bar: # Other group name          
    exclusion_policy: NONE
    properties:
      property_b:
        exclude: true
```
