### ISSUE TITLE
Can I set JSON_FORCE_OBJECT for 1 specific serialization, not for the entire project in config.yml ?

### ISSUE THREAD

**Issue by VaN-dev** [schmittjoh/JMSSerializerBundle#410]
I faced a problem similar to this one : https://github.com/schmittjoh/JMSSerializerBundle/issues/387
So I added in my config.yml : 

```
jms_serializer:    
    visitors:
        json:
            options: [JSON_FORCE_OBJECT]
```

It corrects the initial problem, but now, all my others json parsing are messed up. Is there any way to force the JSON object notation only for 1 specific serialization, in the serialize() method ?

EDIT 
My problem was smartly answered on StackOverflow : https://stackoverflow.com/questions/25450970/jmsserializerbundle-not-mapping-key-equals-to-0
This might help a lot of people.
