### ISSUE TITLE
Serialization manyToOne with yml configutaion

### ISSUE THREAD

**Issue by flohw** [schmittjoh/JMSSerializerBundle#411]
Hi I am trying to serialize two entities with a simple manyToOne relationship using yaml configuration. I have my entities Address (name changed) to one People : (Annotation mapping is correct with a many to one in Address and the other way too)

``` php
namespave Vendor\MyBundle\Entity;
class Address {
    private $id;
    private $zipCode;
    private $people;
}
class People {
    private $id;
    private $addresses;
}
```

And my yml files :

``` yaml
# src/Vendor/MyBundle/Resources/config/serializer/Entity.Address.yml
Vendor\MyBundle\Entity\Address:
    exclusion_policy: ALL
    properties:
        id: { expose: true }
        zipCode: { expose: true }
        people: { expose: true, type: Vendor\MyBundle\Entity\People }

# src/Vendor/MyBundle/Resources/config/serializer/Entity.People.yml
Vendor\MyBundle\Entity\Peple:
    exclusion_policy: ALL
    properties:
        id: { expose: true}
```

When I get my Address entity and return it (api build with fosrestbundle) I get a 502 bad gateway. But when I transform my yaml into annotations, all works fine.

Did I miss someting? thanks for your anwsers!
