### ISSUE TITLE
Serializing traits with JMSSerializer and YAML

### ISSUE THREAD

**Issue by benatespina** [schmittjoh/JMSSerializerBundle#424]
When trying to serialize a model that uses traits, JMSSerializer does not serialize properties included by that trait. I am using yaml to configure the serializer but it seems that it's not working. 

```
trait IdentityTrait
{

    protected $id;

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }
}

class OurClass {
   use IdentityTrait;

   protected $test;

   public function getTest() {
       $this->test;
   }
}
```

JMSSerializerBundle is used and the following yaml is located in `Resources/config/serializer/Model.Traits.IdentityTrait.yml`

```
MyProject\Component\Core\Model\Traits\IdentityTrait:
    exclusion_policy: NONE
    properties:
    id:
        expose: true
```

And the `OurClass` configuration is located in `Resources/config/serializer/Model.OurClass.yml`

```
 MyProject\Component\Core\Model\OurClass:
     exclusion_policy: NONE
     properties:
         test:
             expose: true
```

Some code has been ignored to focus on the problem.

Maybe the trait file name is incorrect?

**Comment by sebastienvermeille** [comment]
I have the same problem I am using KnpDoctrinebehaviors for my translations and jms does not serialize my translated fields. Did you find a workaround ? @benatespina

**Comment by tarlepp** [comment]
So have anyone solution for this?

**Comment by FireLizard** [comment]
Stumbled over the same problem.

**Comment by stephanvierkant** [comment]
See this issue: #102

**Comment by yanict** [comment]
I'm having the same issue (version 1.1.0).
@stephanvierkant, you say that using version 1.4.* is working but this version doesn't seem to even exist.
Could you give more inputs please ?

**Comment by stephanvierkant** [comment]
@yanict I'm using version `1.4.2` of `jms/serializer` and version `1.1.0` of `jms/serializer-bundle`. Please not the difference between the library (serializer) and the bundle that implements it (serializer-bundle).

**Comment by dTrimon** [comment]
Hello, I'm having trouble with this feature too.
Shall the configuration of the serialization be inserted in the hosting entity like in this example:

`Resources/config/serializer/Model.OurClass.yml`

 ```
MyProject\Component\Core\Model\OurClass:
     exclusion_policy: NONE
     properties:
         test:
             expose: true
         id:
             expose: true
```

Or is it possible to define the serialization elswhere, and how?  I tried another file like `banetespina `but it seems never called
