### ISSUE TITLE
New Feature: support multiple configurations

### ISSUE THREAD

**Issue by rkmax** [schmittjoh/JMSSerializerBundle#425]
Currently I need to use the serializer differently at one point in my application, would be excellent if we can declare a default serializer and others with different configurations

Example currently my configuration is

``` yaml
jms_serializer:
    enable_short_alias:   true
    handlers:
        datetime:
            default_format:       'Y-m-d\TH:i:sO'
            default_timezone:     America/Bogota
            cdata:                true
```

maybe can be

``` yaml
jms_serializer:
    default:
        enable_short_alias:   true
        handlers:
            datetime:
                default_format:       'Y-m-d\TH:i:sO'
                default_timezone:     America/Bogota
                cdata:                true
    simple:
        handlers:
            datetime:
                default_format:       'Y-m-d'
                default_timezone:     America/Bogota
                cdata:                true

```

in the code 

``` php
$container->get('serializer'); // return default handler alias to 'serializer_default'
$container->get('serializer_simple') ; // return simple handler
```

**Comment by goetas** [comment]
Should the timezone be stored in the context instead? this will make it even more flexible

**Comment by andreij** [comment]
I have a similar scenario. I some parts of my project I want to use one peculiar visitors configuration:

```
jms_serializer:
  unescaped:    
      visitors:
          json:
              options: JSON_UNESCAPED_SLASHES
```

In order to have some serializations with unescaped strings and other with escaped ones (needed for backward compatibility).

Is it possible to achieve this without multiple configurations?
