### ISSUE TITLE
Can i config groups under virtual_properties?

### ISSUE THREAD

**Issue by liverbool** [schmittjoh/JMSSerializerBundle#505]
This config seem not work. I want to config `groups` under `virtual_properties`. Is it posible?

```yaml
User:
    exclusion_policy: ALL

    virtual_properties:
        getEmail:
            serialized_name: email
            groups: [Detailed]
```
