### ISSUE TITLE
JMSSerializerBundle configuration Metadata

### ISSUE THREAD

**Issue by doums** [schmittjoh/JMSSerializerBundle#536]
Symfony 3.1.7 + FOSRestBundle latest version + JMSSerializerBundle latest version

my files :

>     controller path : /src/PM/ApiBundle/Controller/ArticlesController.php
>     entity path : /src/PM/PlatformBundle/Entity/Article.php
>     config file path : /src/PM/PlatformBundle/Resources/config/serializer/Entity.Article.yml

app/config/config.yml

```
    # JMSSerializer Configuration
    jms_serializer:
        metadata:
            cache: file
            debug: "%kernel.debug%"
            file_cache:
                dir: "%kernel.cache_dir%/serializer"
            #auto_detection: true      I tried this, also doesn't work
            directories:
                PMBundle:
                    namespace_prefix: "PM\\PlatformBundle"
                    path: "@PMPlatformBundle/Resources/config/serializer"
        handlers:
            datetime:
                default_format: "c"
                default_timezone: "UTC"
```
    
controller

```
    <?php
    
    namespace PM\ApiBundle\Controller;
    
    ...
    use FOS\RestBundle\Controller\FOSRestController;
    use FOS\RestBundle\Controller\Annotations as Rest;
    use FOS\RestBundle\View\View;
    use JMS\Serializer\SerializationContext;
    use JMS\Serializer\SerializerBuilder;
    
    
    class ArticlesController extends FOSRestController
    {
        /**
         * @ApiDoc(
         *  section="articles",
         *  resource=true,
         *  description="Get articles published"
         * )
         * @Rest\View()
         * @Rest\Get("/articles")
         */
        public function getArticlesAction(Request $request)
        {
            $serializer = SerializerBuilder::create()->build();
            $articles = $this->getDoctrine()
                ->getManager()
                ->getRepository('PMPlatformBundle:Article')
                ->findAllDateDesc();
            /* @var $articles Article[] */
    
            return $serializer->serialize($articles, 'json', SerializationContext::create()->setGroups(array('article')));
        }
```

entity
```
    <?php
    
    namespace PM\PlatformBundle\Entity;
    
    use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\ORM\Mapping as ORM;
    use Gedmo\Mapping\Annotation as Gedmo;
    use Symfony\Component\Validator\Constraints as Assert;
    use PM\PlatformBundle\Repository\ArticleRepository;
    use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
    use PM\UserBundle\Entity\User;
    
    
    /**
     * Article
     *
     * @ORM\Table(name="article")
     * @ORM\Entity(repositoryClass="PM\PlatformBundle\Repository\ArticleRepository")
     * @UniqueEntity(fields="title", repositoryMethod="findByTitle", message="Un article existe déjà avec ce titre !")
     */
    class Article
    {
        /**
         * @ORM\ManyToMany(targetEntity="PM\UserBundle\Entity\User", inversedBy="liked")
         */
        private $likers;
        ...
```

config

```
    PM\PlatformBundle\Entity\Article:
        exclusion_policy: none
        properties:
            likers:
                exclude: true
            likeCount:
                groups: ['article']
            media:
                exclude: true
            comments:
                groups: ['article']
            id:
                groups: ['article']
            title:
                groups: ['article']
            description:
                groups: ['article']
            author:
                exclude: true
            date:
                groups: ['article']
            lastUpate:
                groups: ['article']
            tags:
                groups: ['article']
            slug:
                groups: ['article']
```

But the rules of this configuration file are not applied because I get this response :

```
    {
    	"0": {},
    	"1": {},
    	"2": {}
    }
```

What's wrong ?

Nota: When I use the Groups annotations (directly in the entity) the serializer works perfectly.

**Comment by sanderfreshheads** [comment]
@Doums Did you ever got it working? I have a similar problem.

**Comment by mathieumuller** [comment]
@Doums @sanderfreshheads same problem too with the yaml metadata file, it seems the node properties is not working at all... Did you found something?

**Comment by acando14** [comment]
Hello,

we detect the same issue on Symfony4, we try to put the configuration of jms directly in the framework.yaml file with this configuration and also in the jms configuration file but with the same result.

```yaml
jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            configuration-database:
                namespace_prefix: "App\\Entity"
                path: "%kernel.root_dir%/../src/Resources/serializer"
```
JMS don't recognize where to find the yaml entity configuration.

If there isn't any solution where could we start to find a soluton on this issue?
