### ISSUE TITLE
Alias not working any more with 1.3

### ISSUE THREAD

**Issue by VincentClair** [schmittjoh/JMSSerializerBundle#559]
It seems that the following configuration not working any more:

```yaml
    acme_app.graphql_validator:
        class: "%acme_app.graphql_validator.class%"
        parent: core_bundle.abstract_service
        arguments:
            - "@serializer"
            - "@validator"

    jms_serializer.object_constructor:
        alias: acme_app.doctrine_object_constructor
        public: false

    acme_app.doctrine_object_constructor:
         class:        Acme\AppBundle\Serializer\DoctrineObjectConstructor
         arguments:    ["@doctrine", "@jms_serializer.unserialize_object_constructor"]
```

The DoctrineObjectConstructor is not called, so the unserialization process does not work (object constructor is not called).

Is there a change with version 1.3 on aliases or some other arguments that could cause this?
It works with previously version 1.2.1.
