### ISSUE TITLE
[BUG] Metadata PhpDriver always beats AnnotationDriver in DriverChain

### ISSUE THREAD

**Issue by akomm** [schmittjoh/JMSSerializerBundle#567]
Problem:

Given classes C1 and C2, while C1 extends C2:
When I deserialize (fromArray) C1 I get an error "can not redeclare class C2".

Found cause:

The DriverChain (jms_serializer.metadata.chain_driver) has following drivers by default (order is important):

- YamlDriver
- XmlDriver
- PhpDriver
- AnnotationDriver

Both PhpDriver and AnnotationDriver accept an annotated .php file. But because PhpDriver is first in order, AnnotationDriver never comes into play. The PhpDriver [requires](https://github.com/schmittjoh/serializer/blob/f7e2818/src/JMS/Serializer/Metadata/Driver/PhpDriver.php#L29) the config resource and that triggers the explained error. 

Overriding the service in  the following way fixes the error:

```yml
  jms_serializer.metadata.chain_driver:
    class: "%jms_serializer.metadata.chain_driver.class%"
    arguments:
      -
        - '@jms_serializer.metadata.yaml_driver'
        - '@jms_serializer.metadata.xml_driver'
        - '@jms_serializer.metadata.annotation_driver' # moved up
        - '@jms_serializer.metadata.php_driver'
```

Not sure who really is responsible for the issue, the serializer bundle or library. Possibilities:
 
1. jms/serializer: The missing acceptance check API in `Metadata\Driver\DriverInterface` and thus missing checks using the API. Currently the use-cases I found always implicate that `null` returned from `loadMetadataForClass` call means "not accepted", but its not phpdoc-annotated and explained in DriverInterface, so I'm not sure.

2. jms/serializer: The bold [require](https://github.com/schmittjoh/serializer/blob/f7e2818/src/JMS/Serializer/Metadata/Driver/PhpDriver.php#L29) in PhpDriver without checking acceptance and returning `null`, before requiring. I see the problem not requiring here thought...

3. jms/serializer-bundle: Actually the root problem seems to be one of the above. When `null` return in 1. is meant to be "not accepted", then 2. is the problem. But I see some complexity when testing acceptance in case 2. before "require". So maybe rearranging the driver chain is in this package is the smarter solution.

**Comment by goetas** [comment]
Are you using annotations or php metadata files?

**Comment by akomm** [comment]
Annotation.

**Comment by goetas** [comment]
How are  configured your paths? ( they should be  not configured at all; and the php driver should never be invoked )

**Comment by akomm** [comment]
```yml
  metadata:
    auto_detection: false
    directories:
      AppMutationInput:
        namespace_prefix: "AppBundle\\GraphQL\\Resolver\\Mutation\\Input"
        path: "%kernel.root_dir%/../src/AppBundle/GraphQL/Resolver/Mutation/Input"
```

I use it to hydrate (fromArray) data transfer objects from graphql mutation queries. With default config it only checks AppBundle\Entities and throws, when I try to hydrate something else.
