### ISSUE TITLE
Yml config should allow to configure the default accessType and readOnly options

### ISSUE THREAD

**Issue by noemi-salaun** [schmittjoh/JMSSerializerBundle#586]
I don't think it's already possible when looking at the [documentation](http://jmsyst.com/bundles/JMSSerializerBundle/master/configuration#extension-reference).

It could be usefull to allow the configuration of the default accessType for the entire project, instead of having to specify `@AccessType("public_method")` in every entities.

Something like :

```yaml
jms_serializer:
    access_type: public_method     # default to 'property'
    read_only: true            # default to false
```
