### ISSUE TITLE
Parent Class Exclude Problem

### ISSUE THREAD

**Issue by safaksaylam** [schmittjoh/JMSSerializerBundle#600]
Hi,
I can use Custom User Bundle and app user extend Custom user. I added @JMS\ExclusionPolicy("all") in class annotation. It was work only this class. Extend class data sets coming. I added jms serializer directories, but it doesn't work. 

**App User Class:**
```php

namespace AppBundle\Entity;

/**
 * @JMS\ExclusionPolicy("all")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\Table(name="user")
 */
class User extends \DPX\AdminBundle\Model\User
{
    use TimestampableEntity, SoftDeleteableEntity;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=255, unique=true)
     */
    protected $username;
 ```

**Custom User Class:**
```php

namespace DPX\AdminBundle\Model;

/**
 * User
 */
abstract class User implements AdvancedUserInterface, \Serializable
{
    use TimestampableEntity;

    /**
     * @var mixed
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     */
    protected $email;
 ```

**config.yml**
```yml
jms_serializer:
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true
        directories:
            CustomAdmin:
                namespace_prefix: Custom\AdminBundle
                path: "%kernel.root_dir%/serializer/CustomAdmin"
 ```
**serializer\CustomAdmin\Model.User.yml**
 ```yml
DPX\AdminBundle\Model\User:
    exclusion_policy: ALL
    properties:
        password:
            exclude: true
```

**JSON Data Example**
```json
user: {
id: 1,
email: "xxxx@gmail.com",
password: "**********************************",
enabled: true,
roles: [
"ROLE_USER"
],
created_at: "2017-06-19T08:05:09+0000",
updated_at: "2017-06-19T11:26:56+0000"
},
```

How can i fixed?
