### ISSUE TITLE
v2.0.0: The "name" property of directories must be given - but must we specify directories?

### ISSUE THREAD

**Issue by narcoticfresh** [schmittjoh/JMSSerializerBundle#607]
Hi guys..

I searched existing and closed issue and couldn't find any information on my small problem. If seen in the `UPGRADING` file, that the `name` key inside `jms_serializer.metadata.directories` must be provided.

Thing is, we never specified any directories. Our config looks like this (and worked fine, only using auto detection):

```yml
jms_serializer:
    handlers:
        datetime:
            default_format: Y-m-d\TH:i:sO
            default_timezone: UTC
    metadata:
        cache: graviton.core.jms.cache.provider
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true
```

So after updating the Bundle to 2.0.0, we get 

```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'The attribute "name" must be set for path "jms_serializer.metadata.directories".' in /src/git/graviton2/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php:244
Stack trace:
#0 /src/git/graviton2/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/BaseNode.php(264): Symfony\Component\Config\Definition\PrototypedArrayNode->normalizeValue(Array)
```

So i guess the question is: Do we really need to specify some directories? What do I define if I don't have anything to specify? ;-)

Thanks for a short clarification
And thanks for your great work!
