### ISSUE TITLE
DateTime custom handler not working

### ISSUE THREAD

**Issue by redayoub** [schmittjoh/JMSSerializerBundle#631]
I'm trying to add a custom handler for DateTime but it's not working. I've tested with other classes and it works.

I'm using the same exact code from the doc.

```php
<?php

namespace AppBundle\Service;

use JMS\Serializer\Handler\SubscribingHandlerInterface;
use JMS\Serializer\GraphNavigator;
use JMS\Serializer\JsonSerializationVisitor;
use JMS\Serializer\Context;

class MyHandler implements SubscribingHandlerInterface
{
    public static function getSubscribingMethods()
    {
        return array(
            array(
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format' => 'json',
                'type' => 'DateTime',
                'method' => 'serializeDateTimeToJson',
            ),
        );
    }

    public function serializeDateTimeToJson(JsonSerializationVisitor $visitor, \DateTime $date, array $type, Context $context)
    {
        return $date->format($type['params'][0]);
    }
}
```
```yaml
my_handler:
  class: AppBundle\Service\MyHandler
  tags:
    - { name: jms_serializer.handler, type: DateTime, format: json } 
```
```php
$date = new \DateTime;
$json = $this->get('jms_serializer')->serialize($date, 'json');
```
