### ISSUE TITLE
Custom handle registration not compatible with Symfony 3.3+

### ISSUE THREAD

**Issue by MrMitch** [schmittjoh/JMSSerializerBundle#641]
Demo repo : https://github.com/MrMitch/jms_handler_registration_issue

# Issue
Hi,
I'm trying to use the ability provided by Symfony 3.3+ to register all the files in a folder as services, tagged the same way, without having to tag them individually.
Symfony does this, for example, to [register all controllers as services](
https://github.com/symfony/demo/blob/4a61d2824fb083419b8153bf8d566fb529c98485/config/services.yaml#L30-L32) and tag them with the `controller.service_arguments` tag.

I'm trying to apply the same reasoning to register all the custom serialization handlers in my `Serialization\SubscribingHandlers` folder, but this doesn't work.
```yml
AppBundle\Serialization\SubscribingHandlers\:
    resource: '../../src/AppBundle/Serialization/SubscribingHandlers/*'
    tags: ['jms_serializer.subscribing_handler']
```

The files are registered as services but they are not used by the serializer.
Specifically, I'm trying to register a `DateTime` handler that would deserialize `''` as `null`. The DateTime handler that I try to register is not invoked. Instead, the default `DateHandler` provided by the bundle is used (and it fails because it tries to deserialize `''`).

![image](https://user-images.githubusercontent.com/576772/37206647-d8d29f18-2399-11e8-9238-e3c4ebc2a9f8.png)

# Findings

If I change my service declaration to this : 
```yml
jms_serializer.datetime_handler:
    class: AppBundle\Serialization\SubscribingHandlers\TreatEmptyStringAsNullDateTimeHandler
    tags: ['jms_serializer.subscribing_handler']
```
 Then the right handler is called, but this has several drawbacks : 
- the service name has to specifically be `jms_serializer.datetime_handler` and nothing else
- I have to separately declare each handler

I've made a demo repository with the minimum code to test this : https://github.com/MrMitch/jms_handler_registration_issue

The [`master`](https://github.com/MrMitch/jms_handler_registration_issue/tree/master) branch has the code with the Symfony-style service declaration that doesn't work, the [`working`](https://github.com/MrMitch/jms_handler_registration_issue/tree/working) branch has the working service declaration (not Symfony-style).

Please let me know if I can provide you with any more information.

**Comment by goetas** [comment]
This is about registration priorities. This bundle offers a handler for the date time object.

If you want to override the default behavior you have some options: 
1. remove the `jms_serializer.datetime_handler` and then register your custom handler
2. make sure that your handler is registered with the right priority (to override the default one)
3. make a PR to this bundle allowing to disable `jms_serializer.datetime_handler`

**Comment by PGLongo** [comment]
I've found another quick&dirty workaround, giving the same name to the service:

```yaml
#config\services.yaml

jms_serializer.datetime_handler:
  class: App\EventListener\DateTimeSerializerHandler
  tags:
      - { name: jms_serializer.subscribing_handler}
```

**Comment by goetas** [comment]
fixed in https://github.com/schmittjoh/JMSSerializerBundle/pull/645

**Comment by MrMitch** [comment]
great, thank you for taking it into account.
Is there a place in the docs that explains how to do this with the corrections applied in #645 ?

**Comment by goetas** [comment]
```yaml
#config\services.yaml

your_handler:
  class: App\EventListener\DateTimeSerializerHandler
  tags:
      - { name: jms_serializer.subscribing_handler, priority: -10}
```

**Comment by MrMitch** [comment]
thank you very much, i really appreciate the feedback!

**Comment by MrMitch** [comment]
My original question was more about registering all the files in a folder as services, tagged the same way, without having to tag them individually.
Would this work with this configuration ?

```yaml
AppBundle\Serialization\SubscribingHandlers\:
  resource: '../../src/AppBundle/Serialization/SubscribingHandlers/*'
  tags:
      - { name: jms_serializer.subscribing_handler, priority: -10}
```
