### ISSUE TITLE
JMSSerializerBundle configuration Metadata (2)

### ISSUE THREAD

**Issue by aayaresko** [schmittjoh/JMSSerializerBundle#650]
hello. first of all: thanks a lot for this wonderful bundle. it's very useful. 
I have an issue with jms/serializer-bundle: 2.3.1 and symfony 4.0.6. When react app retrieves the data, it receives empty objects:
````
[
    0: {},
    1: {},
    2: {},
    3: {},
    4: {},
]
````

Here's the content of jms_serializer.yaml
````
jms_serializer:
    metadata:
        cache: file
        debug: '%kernel.debug%'
        file_cache:
            dir: '%kernel.cache_dir%/serializer'
        auto_detection: false
        directories:
            app:
                namespace_prefix: "App\\Entity"
                path: "%kernel.root_dir%/Resources/config/serializer"
    property_naming:
        separator:  _
        lower_case: true
    handlers:
        datetime:
            default_format: 'Y-m-d\TH:i:sO'
            default_timezone: 'UTC'
````
Here is my song entity serialization config (src/Resources/config/serializer/Entity.Song.yml)
````
App\Entity\Song:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [view_default, view_detailed]
        aliasName:
            expose: true
            groups: [view_default, view_detailed]
        file:
            expose: true
            groups: [view_default, view_detailed]
        createdAt:
            expose: true
            groups: [view_detailed]
        deletedAt:
            expose: true
            groups: [view_detailed]
        tags:
            expose: true
            groups: [view_detailed]
        playLists:
            expose: true
            groups: [view_detailed]
    virtual_properties:
        getName:
            serialized_name: name
            type: string
            groups: [view_default, view_detailed]
        getArtist:
            serialized_name: artist
            type: string
            groups: [view_default, view_detailed]
        getWebPath:
            serialized_name: web_path
            type: string
            groups: [view_default, view_detailed]
````
Controller
````
<?php

namespace App\Controller\API;

use App\Entity\PlayList\PlayList;
use App\Entity\Song\SongTag;
use App\Repository\Song\SongTagRepository;
use App\Service\PlayListService;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Rest\Route("user")
 */
class SongController extends ApiController
{
    /**
     * @Rest\Get("/play-list/{id}/song", name="api.user.play_list.song")
     *
     * @param PlayList $entity
     * @return Response
     */
    public function playListSongs(PlayList $entity)
    {
        /** @var PlayListService $service */
        $service = $this->get(PlayListService::class);
        $view    = $this->view($service->retrieveSongs($entity), Response::HTTP_OK, ['view_default']);

        return $this->handleView($view);
    }
}
````

I have no idea why it doesn't work. It worked fine with model annotations but completely broken now, with yml configs. Need some help :) Thanks in advance.

ps: bundle is enabled (bundles.php);
all steps, described in #536 are done and checked without any success
