### ISSUE TITLE
XML serialization version and encoding configuration

### ISSUE THREAD

**Issue by benjhoo** [schmittjoh/JMSSerializerBundle#661]
Hi,
by default, XML serialization provide data with the starter line `<?xml version="1.0" encoding="UTF-8"?>`

Is there a way to configure the version and the encoding type of an XML serialization ?

I tried the following configuration I've found in documentation :
```
# config.yml
jms_serializer:
    ...
    visitors:
        json_serialization:
            options: 0 # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
            depth: 512
        json_deserialization:
            options: 0 # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
        json_serialization:
            format_output: false
            version: "1.1"
            encoding: "ISO-8859-15"
            default_root_name: "result"
            default_root_ns: null
        json_deserialization:
            external_entities: false
            doctype_whitelist:
                - '<!DOCTYPE authorized SYSTEM "http://some_url">' # an authorized document type for xml deserialization
```

But Symfony returns the following error :
```
Unrecognized options "json_serialization, json_deserialization" under "jms_serializer.visitors"
```

My Symfony version is **2.7**

Thanks
