### ISSUE TITLE
Excluding FOSUserBundle properties 

### ISSUE THREAD

**Issue by ergineker** [schmittjoh/JMSSerializerBundle#668]
I'm using Symfony 4.1 and I'm following this configuration:

config/packages/jms_serializer.yaml :

```
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\UserBundle"
                path: '%kernel.root_dir%/serializer/FOSUserBundle'
```

src/serializer/FOSUserBundle/Model.User.yml :

```
FOS\UserBundle\Model\User:
    exclusion_policy: all
    properties:
    id:
        expose: true
```

I want to include only **ID** to my serialized data, but all the FOSUserBundle properties came  together. I tried cache clear etc.. How can I fix this?

**Comment by ergineker** [comment]
I found the solution. I'm using this settings and it works.

config/packages/jms_serializer.yaml
```
jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/Serializer/FOSUB"
```

src/Serializer/FOSUB/Model.User.yml
```
FOS\UserBundle\Model\User:
    exclusion_policy: none
    properties:
        emailCanonical:
            exclude: true
        usernameCanonical:
            exclude: true
        password:
            exclude: true
        lastLogin:
            exclude: true
        roles:
            exclude: true
        enabled:
            exclude: true
```
