### ISSUE TITLE
Filelocator is not called in Symfony 4

### ISSUE THREAD

**Issue by mehdi-zarrin** [schmittjoh/JMSSerializerBundle#686]
Hi, 
I'm using Symfony 4 + FOSUserBundle for security reasons I have to hide some fields (email, password,..). For some reason, the metadata file locator is not called after I call the serialize method in a controller. Here is my configuration: 

packages/jms_serializer.yaml
```
jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: "%kernel.root_dir%/serializer"
```
src/serializer/FOSUB/Model.User.yml
```
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        firstName:
            expose: true
```

**Comment by mehdi-zarrin** [comment]
I tried that before but that did not solve my issue. By the way, I change just the way you said but still, Exclusion policy is not happening for me.

**Comment by goetas** [comment]
I have updated the docs about this issue right few days ago... can you check that you did all the things in https://github.com/schmittjoh/JMSSerializerBundle/commit/6f45a525d1872fc533c0f40103ce0dda2ba70e57 ?

**Comment by goetas** [comment]
See the `\\` as example... 99% of the cases this kind of issues were always mis-configurations.

**Comment by mehdi-zarrin** [comment]
I think I follow the documentation exactly, here is my directory structure: 
```
- src 
--- serializer 
----- FOSUB
-------- Model.User.yml
```
```
jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"
```
