### ISSUE TITLE
serialize_null config option simply ignored

### ISSUE THREAD

**Issue by vincent-dravert** [schmittjoh/JMSSerializerBundle#699]
Symfony 4.1.7
JMS Serializer 2.0.0

The following option is being ignored so null properties are ignored from output.

```
jms_serializer:
        default_context:
                serialization:
                    serialize_null: true
```
I needed to use

`setSerializeNull(true)`

on each use of the serializer
