### ISSUE TITLE
[Question] why is the StdClassHandler not enabled per default?

### ISSUE THREAD

**Issue by leberknecht** [schmittjoh/JMSSerializerBundle#727]
Ahoi!

I noticed that i have to define a service like 
```yaml
    jms.enable_std_handler:
        class: JMS\Serializer\Handler\StdClassHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
```
to register the `StdClassHandler`. Why is it not enabled per default like the rest? Or am i missing something?
