### ISSUE TITLE
Attempted to call an undefined method named "setDepth" of class "JMS\Serializer\Visitor\Factory\JsonSerializationVisitorFactory".

### ISSUE THREAD

**Issue by plamenh** [schmittjoh/JMSSerializerBundle#751]
Just upgraded from 2.x to 3.x and this is the error I get. It seems to be related to:

```
visitors:
        json_serialization:
            options: 0 # json_encode options bitmask, suggested JSON_PRETTY_PRINT in development
            depth: 512
```

However, when I remove the depth option, I get:

`Context visitingStack not working well`
