### ISSUE TITLE
JSON Serialization Options seem to be ignored

### ISSUE THREAD

**Issue by Vorta** [schmittjoh/JMSSerializerBundle#763]
Symfony: v4.3.2
willdurand/hateoas: v3.1.0
jms/serializer: v3.1.1
jms/serializer-bundle: v3.4.1

I may be missing something, however I've noticed that I'm getting escaped slashes in my serialized output, even though my config looks as follows:

```
jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
            encoding: 'UTF-8'
        json_serialization:
            options: ['JSON_PRETTY_PRINT', 'JSON_UNESCAPED_SLASHES']
```

I've tried setting `options:` in other ways too:
```
   ...
            options:
                - JSON_PRETTY_PRINT
                - JSON_UNESCAPED_SLASHES
```

If I deliberately mistype a key, I get an error, so it shows that they are being read. However, the output is not being changed. Slashes are escaped and pretty print is not being performed.

If I dump `$options` in JsonSerializationVisitor.php, I can see that only the default `JSON_PRESERVE_ZERO_FRACTION` flag is being used. I have tried to find where are Options from the config being used, however, I was unsuccessful.
