### ISSUE TITLE
[Metadata] Collision when using empty namespace_prefix

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSSerializerBundle#769]
I'm using the JMSSerializerBundle and have a problem. I register my serialization config as YAML with the following config:
```yaml
jms_serializer:
    metadata:
        auto_detection: false
        directories:
            DomainEntity:
                namespace_prefix: ~
                path: "@MyBundle/Resources/config/serializer"
```

As you can see, I have `auto_detection: false` and leave the `namespace_prefix` empty, because I want to register multiple namespaces that don't share a common prefix. This works great!

But now I installed a 3rd-party bundle that does this:
https://github.com/kunicmarko20/jms-messenger-adapter/blob/dd8c1b3282b3effc8f1287035e6ec82912b21402/src/Bridge/Symfony/DependencyInjection/JMSMessengerAdapterExtension.php#L44-L52

It also registers multiple namespaces: https://github.com/kunicmarko20/jms-messenger-adapter/tree/master/src/Resources/config/serializer

The problem is that the Serialization configuration from the `jms-messenger-adapter` gets overwritten by my declaration because we both use an empty prefix. The prefix is then transformed to an empty string key. 

When I look at the internals, I see that the directories array is generated and then passed to the FileLocator:
https://github.com/schmittjoh/JMSSerializerBundle/blob/9b8d64302770183b41c47d3c38c67aa9ae1c970b/DependencyInjection/JMSSerializerExtension.php#L126-L150

An easy fix could be to make the `$this->dirs` array multi dimensional:
https://github.com/schmittjoh/metadata/blob/d2ef520eb331e00bddd1b9306eecca9302c57f16/src/Driver/FileLocator.php#L24-L34

If a duplicate (or empty) prefix is registered, it will be appended to the array. 

@goetas Before I make a PR, I would like to know if you have objections against this and if it's the way to go.
