### ISSUE TITLE
Disable serializer for FOSUserBundle entities

### ISSUE THREAD

**Issue by ruudk** [schmittjoh/JMSSerializerBundle#78]
I am using the FOSUserBundle and have my own entity extended of the FOSUserBundle Model.

In my user entity I want to serialize some things. But the rest should be excluded.

So I added `@Serializer\ExclusionPolicy("all")` but somehow all the UserBundle's properties are exposed.

In my cache directory I keep getting this file: `serializer/FOS-UserBundle-Model-User.cache.php`.

How can I get rid of this?

**Comment by igorladela** [comment]
+1 @cambot 
How you resolve the issue?

**Comment by cambot** [comment]
@igorladela, the project I was working on ended up writing custom functions to provide arrays containing subsets of the entity fields.  We were already doing this to provide several different views for the same entity, so it was an easy way for us to get around this issue too.

**Comment by skonsoft** [comment]
Solution as described in #78  Works after clearing the cache :+1:

**Comment by smilesrg** [comment]
@mvrhov  @schmittjoh @skonsoft @PierrickMartos @geoffreytran @hpatoio @stof Tried all these solutions and they doesn't work. Even after clearing the cache. What reason could be?

My config is:

```yaml
#app/config/config.yml
jms_serializer:
    metadata:
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"
```

```yaml
#app/serializer/FOSUB/User.yml
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            groups: [Registration, Profile, Default]
        # enabled:
        #     expose: true
        # locked:
        #     expose: true
```

```php
<?php
//src/UserBundle/Entity/User.php
namespace UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="users")
 */
class User extends BaseUser
{
```

**Comment by marijnz0r** [comment]
@smilesrg 

My friend, you have to name your file as Model.User.yml

Before:
```
#app/serializer/FOSUB/User.yml
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            groups: [Registration, Profile, Default]
        # enabled:
        #     expose: true
        # locked:
        #     expose: true
```
After:
```
#app/serializer/FOSUB/Model.User.yml
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
            groups: [Registration, Profile, Default]
        # enabled:
        #     expose: true
        # locked:
        #     expose: true
```

And then, of course, change the file name as well.

Let me know if this helped you.

**Comment by stof** [comment]
the other solution if you want to keep the file name as ``User.yml`` is to change the namespace prefix in your config (to include the ``Model`` part there)

**Comment by Mortagus** [comment]
Hello everybody,

I've got a very similar problem into my project.
The only difference is : I'm not using the FOSUB.

I'm working on an API and I need to exclude some fields from my entities when they are requested.
I'm using the FosRestBundle and I can't make my JMSSerializer annotations work !

I try to implement the solutions presented here, but nothing works.

Does somebody can help me ?

**Comment by bruno-ds** [comment]
Hello, I've spent a lot of time on these pitfalls, maybe the doc could have a tooltip to help prevent them : 

- if you have inheritance, you can only alter the serialisation of the fields owned by the class, not by its parents (see point 2 for overwriting the parents)
- in case of third party redefinition : you can cascade the definitions and only overwrite the serialization of one entity, for the others, the serializer will fall back to the third party definition.
- in the `namespace_prefix` config. you can aim to partial namespace, in this case, the serialization config file name must complete the lacking part, for example : for a class `Foo\Bar\Baz\Toto\EntityName` with `namespace_prefix: "Foo\\Bar"`, the serialization config file name must be "Baz.Toto.EntityName.yml"
- in the `namespace_prefix`  use double quotes, and escape the backslashes

**Comment by mehdi-zarrin** [comment]
> Yes, a lot of times. And I've tried a lot of combinations for `namespace_prefix: "FOS\\UserBundle"`configuration. Is anyone else having the same problem? Thanks!

I'm using SF4 and I have the same issue have you figure out your problem?

**Comment by reskume** [comment]
In addition to @bruno-ds comment, it may also be helpful to note that when overwriting third-party metadata, only files with the `.yml` extension are picked up. Files with `.yaml` seem to be ignored, at least for my setup...

**Comment by picks44** [comment]
Hi guys,

Since my upgrade to Symfony 3.4, I can't serialize the `Fos/UserBundle/Model/User` class attributes (username, email...). It was working fine in version 2.8 of Symfony...
I'm using v2.4.3 of JMSSerializer.

Here is my config

**config.yml**
```
# JmsSerializer Configuration
jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUB"
```

**Model.User.yml** (in app/serializer/FOSUB)
```
FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [details, chats, devices]
        username:
            expose: true
            groups: [details, devices]
        email:
            expose: true
            groups: [details]
        roles:
            expose: true
            groups: [details]
```

Now my API doesn't return me any attributes from the thrid-party class
`Neither the property "username" nor one of the methods "getUsername()", "username()", "isUsername()", "hasUsername()", "__get()" exist and have public access in class "stdClass".`

Any clue?
