### ISSUE TITLE
I Can't configure exclusion groups in Symfony 5

### ISSUE THREAD

**Issue by fjugaldev** [schmittjoh/JMSSerializerBundle#785]
Hi guys..

I'm trying to add some excluding groups and i can't make work this configuration.

I'm using symfony 5 and this is my config:
```yaml
#config/packages/jms_serializer.yaml
jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
        json_deserialization:
            options:
                - JSON_HEX_AMP
                - JSON_HEX_APOS
                - JSON_HEX_QUOT
                - JSON_HEX_TAG
    metadata:
        auto_detection: false
        directories:
            InnovatikLabs:
                namespace_prefix: "InnovatikLabs\\Shared\\Domain\\Model"
                path: "%kernel.project_dir%/src/Shared/Infrastructure/Serializer"
```

```yaml
#src/Shared/Infrastructure/Serializer/Address.yml
InnovatikLabs\Shared\Domain\Model\Address:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [detail]
        street:
            expose: true
            groups: [detail]
        postalCode:
            expose: true
            groups: [detail]
        phone:
            expose: true
            groups: [detail]
```

My Model is in `InnovatikLabs\Shared\Domain\Model\Address` and the mapping is made using xml.

When i execute a doctrine find in my controller i get an Address object and when i return a JsonResponse like this:

```php
$em = $this->getDoctrine()->getManager();
$address = $em->getRepository(Address::class)->find('298a2773-ab9f-4225-877d-1fe80acf60b5');

return JsonResponse::create(
    $serializer->serialize($address, 'json', SerializationContext::create()->setGroups(['detail']))
);
```

The response is empty.

I think i'm missing something or i guess the bundle is no reading my config in order to get the excluding groups from the yaml's.

**Note: If i use the method addMetadataDir like this:**
```php
$serializer = SerializerBuilder::create()
    ->addMetadataDir('/var/www/html/src/Shared/Infrastructure/Serializer')
    ->build();
```
And renaming the .yml containing the serialization groups, in order to include all the namespace like `InnovatikLabs.Shared.Domain.Model.Address.yml`, it works! but i need an automated way to declare all my config and serialization groups and only stay focus in serializa and deserialize objects.

Can anybody help me please xD
