### ISSUE TITLE
The format_output option is not working ?

### ISSUE THREAD

**Issue by NicolasFz** [schmittjoh/JMSSerializerBundle#794]
I wanted to remove the indentation from my XML output, but the format_output option doesn't seem to work.
The other options seem to work well.

My config/packages/jms_serializer.yaml file : 
```
jms_serializer:
    visitors:
        xml_serialization:
            format_output: false
    property_naming:
        id: 'jms_serializer.identical_property_naming_strategy'
```

My jms bundle version : 
```
jms/serializer:3.6.0  
jms/serializer-bundle :3.5.0
```

Is that a bug or did I miss someting on the configuration documentation ?
