### ISSUE TITLE
[BUG] console cache:clear does not clear the cache

### ISSUE THREAD

**Issue by yyaremenko** [schmittjoh/JMSSerializerBundle#834]
When I execute
```
./bin/console cache:clear --env=<ENV>
```
I expect the bundle's corresponding environment <ENV> cache to be cleared, but it does not. Instead, I have to manually delete it
```
rm -rf var/cache/<ENV>/jms_serializer/*
```
related ticket [734](https://github.com/schmittjoh/JMSSerializerBundle/issues/734)

**Comment by gam6itko** [comment]
@yyaremenko can you show your `jms_serializer` config ?

```
php bin/console debug:config jms_serializer
```

**Comment by gam6itko** [comment]
It's not actually a bug. To cache jms metadata the `Metadata\ClassMetadata\FileCache` class is used. Symfony doesn't know about this metadata cache and can't clear it. 

To clear the jms metadata cache by `cache:clear` command you need to wrap the built-in Symphony cache with `PsrCacheAdapter`

```
# config/packages/jms_serializer.yaml
services:
    jms.metadata_cache:
        class: Metadata\Cache\PsrCacheAdapter
        arguments: ["cache_app_jms_serializer_%kernel.environment%", "@cache.app"]

jms_serializer:
    metadata:
        cache: jms.metadata_cache
```

We need a documentation section about this.
