### ISSUE TITLE
ArrayCollection handler without manager

### ISSUE THREAD

**Issue by vytenis-sciukas-nfq** [schmittjoh/JMSSerializerBundle#955]
Why JMS\Serializer\Handler\ArrayCollectionHandler is without ManagerRegistry out of the box?
Im unable to find info about this case, but only adding ManagerRegistry my collection deserialization started working properly

```
    jms_serializer.array_collection_handler:
        class: JMS\Serializer\Handler\ArrayCollectionHandler
        public: false
        arguments:
            - false
            - '@doctrine'
        tags:
            - { name: 'jms_serializer.subscribing_handler' }
```
